added missing mob IDs
CatsAndBoats/catseyexi pull request #127
Opened 2022-11-02 04:26 UTC by JayTDawgzone

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

## Steps to test these changes

2022-11-02 17:55 UTC, CatsEyeXI commented
@JayTDawgzone since you prefer to do it this way (hardcode the mob ID's into the zone ID.lua), I suggest we use DYNAMIC_LOOKUP to shift proof your work... 

`scripts/zones/Arrapago_Reef/IDs.lua`

is a good example, see how Medusa is set up as a dynamic lookup.

2022-11-02 17:57 UTC, CatsEyeXI requested changes

2022-11-02 17:57 UTC, CatsEyeXI commented on scripts/zones/Labyrinth_of_Onzozo/IDs.lua
> +        LORD_OF_ONZOZO          = 17093078,
Convert to dynamic lookup

2022-11-02 17:57 UTC, CatsEyeXI commented on scripts/zones/Mamook/IDs.lua
> +        HUNDREDFACED_HAPOOL_JA   = 17043665,
Convert to Dynamic Lookup

2022-11-02 17:57 UTC, CatsEyeXI commented on scripts/zones/RoMaeve/IDs.lua
> +        SHIKIGAMI_WEAPON  = 17277127,
Convert to Dynamic Lookup

2022-11-02 17:57 UTC, CatsEyeXI commented on scripts/zones/Wajaom_Woodlands/IDs.lua
> +        HYDRA                  = 16986355,
Convert to Dynamic Lookup

2022-11-02 17:58 UTC, CatsEyeXI commented
also, the pull request template contains 3 checkboxes, please make sure you complete and mark them complete .

![image](https://user-images.githubusercontent.com/65316697/199566140-ea3bf46a-3ba9-4a31-9c0e-081089c64225.png)

2022-11-03 03:21 UTC, JayTDawgzone commented
Will do, I was going to make a data table in the module to remove any dependency from the scripts, but ended up doing this on Hax's advice. It appears that I have some more work to do in the database tables in modules anyways, so I'll close this for now and come back to it.

2022-11-03 03:21 UTC, closed without merging